# log4j.rootLogger = INFO, File
log4j.rootLogger = INFO, File, stdout

# Define the root logger with appender for file
log4j.appender.File=org.apache.log4j.DailyRollingFileAppender
log4j.appender.File.File=${logfile.name}
log4j.appender.File.layout=org.apache.log4j.PatternLayout
log4j.appender.File.layout.ConversionPattern=[%-5p] %d{ISO8601} %c - %m%n

# Define the root logger with appender for console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%-5p] %d{ISO8601} %c - %m%n
